/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import Classes.User;
import Handler.DatabaseHandler;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 * The Form which is only accessable for Admins for them to monitor the users
 * @author patricia
 */
public class AdminForm extends javax.swing.JPanel {

    private ArrayList<User> user = new ArrayList<>();
    private DefaultTableModel userModel = new DefaultTableModel();
    private DatabaseHandler AllEvents_user = new DatabaseHandler();

    /**
     * Creates new form AdminForm
     */
    public AdminForm(ArrayList<Classes.User> user) {
        this.user = user;
        initComponents();
        setContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bottom = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Center = new javax.swing.JPanel();
        CenterLeft = new javax.swing.JPanel();
        CenterLeftTop = new javax.swing.JPanel();
        jLListeOfUsers = new javax.swing.JLabel();
        CenterLeftCent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        CenterRight = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        Top.setBackground(new java.awt.Color(196, 209, 248));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("~ Admin Interface ~");

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                .addContainerGap())
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(Top, java.awt.BorderLayout.PAGE_START);

        Bottom.setBackground(new java.awt.Color(196, 209, 248));

        jButton1.setText("Back to Calendar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BottomLayout = new javax.swing.GroupLayout(Bottom);
        Bottom.setLayout(BottomLayout);
        BottomLayout.setHorizontalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(677, Short.MAX_VALUE))
        );
        BottomLayout.setVerticalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        add(Bottom, java.awt.BorderLayout.PAGE_END);

        CenterLeft.setLayout(new java.awt.BorderLayout());

        jLListeOfUsers.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLListeOfUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLListeOfUsers.setText("~ List of All Users  ~");

        javax.swing.GroupLayout CenterLeftTopLayout = new javax.swing.GroupLayout(CenterLeftTop);
        CenterLeftTop.setLayout(CenterLeftTopLayout);
        CenterLeftTopLayout.setHorizontalGroup(
            CenterLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLeftTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLListeOfUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        CenterLeftTopLayout.setVerticalGroup(
            CenterLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLeftTopLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLListeOfUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        CenterLeft.add(CenterLeftTop, java.awt.BorderLayout.PAGE_START);

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "First Name", "Last Name", "Email", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(UserTable);

        javax.swing.GroupLayout CenterLeftCentLayout = new javax.swing.GroupLayout(CenterLeftCent);
        CenterLeftCent.setLayout(CenterLeftCentLayout);
        CenterLeftCentLayout.setHorizontalGroup(
            CenterLeftCentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLeftCentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        CenterLeftCentLayout.setVerticalGroup(
            CenterLeftCentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLeftCentLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );

        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);

        CenterLeft.add(CenterLeftCent, java.awt.BorderLayout.CENTER);

        CenterRight.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout CenterLayout = new javax.swing.GroupLayout(Center);
        Center.setLayout(CenterLayout);
        CenterLayout.setHorizontalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addComponent(CenterLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(CenterRight, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        CenterLayout.setVerticalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CenterLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CenterRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        add(Center, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * if you double tap on a chosen dataset of a {@link User}
     * the user editor interface {@link EditUserForm} will open
     * @param evt 
     */
    private void UserTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTableMousePressed
        if (evt.getClickCount() == 2) {
            CenterRight.removeAll();
            CenterRight.revalidate();
            CenterRight.repaint();
            int row = UserTable.getSelectedRow();
            EditUserForm JPEditUser = new EditUserForm(user.get(row), AllEvents_user.getUsersEvents(user.get(row)));
            CenterRight.add(JPEditUser);
            JPEditUser.setVisible(true);
        }
    }//GEN-LAST:event_UserTableMousePressed
    
    /**
     * closes the form, and returns back to the mainframe
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Window JDialog = SwingUtilities.getWindowAncestor(this);
        JDialog.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * sets the content of the {@link JTable} respectively to the users in the 
     * database
     */
     private void setContent() {
        userModel = (DefaultTableModel) UserTable.getModel();

        for (Classes.User u : this.user) {
            userModel.addRow(
                    new Object[]{
                        u.getUsername(),
                        u.getFirstname(),
                        u.getLastname(),
                        u.getEmail(),
                        u.getRoleName()
                    });
        }
        UserTable.setModel(userModel);
        //UserTable.setRowSelectionAllowed(true);
        UserTable.setColumnSelectionAllowed(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Center;
    private javax.swing.JPanel CenterLeft;
    private javax.swing.JPanel CenterLeftCent;
    private javax.swing.JPanel CenterLeftTop;
    private javax.swing.JPanel CenterRight;
    private javax.swing.JPanel Top;
    private javax.swing.JTable UserTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLListeOfUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
