/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Handler.UserHandler;
import Handler.DatabaseHandler;
import Classes.User;
import Handler.EncryptionHandler;
import java.util.Arrays;

/**
 * Form with which users are able to create their own accounts 
 * @author patricia
 */
public class RegistrationForm extends javax.swing.JFrame {

    //Class Variables
    DatabaseHandler dbHandler = new DatabaseHandler();
    UserHandler uHandler = new UserHandler();
    User new_user = null;

    /**
     * Creates new form Registration
     */
    public RegistrationForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_LogToRegistration_Log = new javax.swing.JLabel();
        jLabel_firstname = new javax.swing.JLabel();
        jLabel_lastname = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_emailConf = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jLabel_passwordConf = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_emailConfirmation = new javax.swing.JTextField();
        button_registration = new javax.swing.JButton();
        jLabel_aggreToC = new javax.swing.JLabel();
        pw_password = new javax.swing.JPasswordField();
        pw_passwordConfirmation = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration");

        jPanel1.setBackground(new java.awt.Color(234, 238, 252));

        jPanel2.setBackground(new java.awt.Color(196, 209, 248));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registration");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(196, 209, 248));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel_LogToRegistration_Log.setText("already have an account ? click here to go back to log in ");
        jLabel_LogToRegistration_Log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_LogToRegistration_Log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LogToRegistration_LogMouseClicked(evt);
            }
        });

        jLabel_firstname.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_firstname.setText("Firstname : ");

        jLabel_lastname.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_lastname.setText("Lastname :");

        jLabel_username.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_username.setText("Username :");

        jLabel_email.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_email.setText("Email :");

        jLabel_emailConf.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_emailConf.setText("Email confirmation :");

        jLabel_password.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_password.setText("Password :");

        jLabel_passwordConf.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_passwordConf.setText("Password confirmation :");

        button_registration.setText("register*");
        button_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registrationActionPerformed(evt);
            }
        });

        jLabel_aggreToC.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel_aggreToC.setText("*by clicking the registration button you agree our terms of condition");

        pw_password.setText("jPasswordField1");

        pw_passwordConfirmation.setText("jPasswordField2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_registration, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel_aggreToC)
                        .addComponent(jLabel_LogToRegistration_Log)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel_passwordConf)
                            .addGap(20, 20, 20)
                            .addComponent(pw_passwordConfirmation, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_lastname)
                                .addComponent(jLabel_username)
                                .addComponent(jLabel_email)
                                .addComponent(jLabel_emailConf)
                                .addComponent(jLabel_password)
                                .addComponent(jLabel_firstname))
                            .addGap(45, 45, 45)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(txt_lastname)
                                .addComponent(txt_username)
                                .addComponent(txt_email)
                                .addComponent(txt_emailConfirmation)
                                .addComponent(pw_password)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_LogToRegistration_Log)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_firstname)
                    .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_lastname)
                    .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_username)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_email)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_emailConf)
                    .addComponent(txt_emailConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_password)
                    .addComponent(pw_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_passwordConf)
                    .addComponent(pw_passwordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_registration)
                .addGap(5, 5, 5)
                .addComponent(jLabel_aggreToC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * go back to the Log IN
     * @param evt mouse click
     */
    private void jLabel_LogToRegistration_LogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LogToRegistration_LogMouseClicked
        //close Registration in GUI and create/open an log in GUI
        Login Login = new Login();
        Login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_LogToRegistration_LogMouseClicked
    /**
     * Button to create an account if the given user input is valid
     * @param evt mouse click
     */
    private void button_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registrationActionPerformed
        // TODO add your handling code here: Register new User

        //read the textfields 
        String reg_firstname = txt_firstname.getText();
        String reg_lastname = txt_lastname.getText();
        String reg_username = txt_username.getText();
        String reg_email = txt_email.getText();
        String reg_emailConfirmation = txt_emailConfirmation.getText();
        String reg_password = Arrays.toString(pw_password.getPassword());
        String reg_passwordConfirmation = Arrays.toString(pw_passwordConfirmation.getPassword());
        
        Classes.Registration toBeRegistered
                = new Classes.Registration(reg_username,
                        reg_firstname,
                        reg_lastname,
                        reg_email,
                        reg_password,
                        reg_emailConfirmation,
                        reg_passwordConfirmation);

        if (uHandler.tryToCreateNewUser(toBeRegistered)) {
            boolean emailAvailable = dbHandler.UserEmailAvailable(toBeRegistered);
            boolean usernameAvailable = dbHandler.UserNameAvailable(toBeRegistered);
            if (!emailAvailable && !usernameAvailable) {
                javax.swing.JOptionPane.showMessageDialog(this, "Email & Username not Available");
            } else if (!emailAvailable) {
                javax.swing.JOptionPane.showMessageDialog(this, "Email not Available");
            } else if (!usernameAvailable) {
                javax.swing.JOptionPane.showMessageDialog(this, "Username not Available");
            } else {
                new_user = uHandler.createNewUser(toBeRegistered, emailAvailable, usernameAvailable);
                String encrypted_password = EncryptionHandler.encryptPassword(pw_password.getPassword());
                dbHandler.createNewUser(new_user, encrypted_password);
                MainFrame main = MainFrame.getObject();
                main.setConfigurations(new_user);
                main.setVisible(true);
                this.dispose();
            }

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "User Input was wrong! Try again");
        }
    }//GEN-LAST:event_button_registrationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegistrationForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_registration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_LogToRegistration_Log;
    private javax.swing.JLabel jLabel_aggreToC;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_emailConf;
    private javax.swing.JLabel jLabel_firstname;
    private javax.swing.JLabel jLabel_lastname;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_passwordConf;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField pw_password;
    private javax.swing.JPasswordField pw_passwordConfirmation;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_emailConfirmation;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
